### ISSUE TITLE
Data Transfer of Run1.2p DRP data products from IN2P3 to NERSC

### ISSUE THREAD

**Issue by heather999** [LSSTDESC/ImageProcessingPipelines#43]
As discussed at today's DM-DC2 meeting, we will coordinate the transfer of data from IN2P3 to NERSC.  This issue will capture the list of files to transfer and the destination directory.

At NERSC: /global/projecta/projectdirs/lsst/global/in2p3 
I would recommend setting up a new subdirectory Run1.2p

**Comment by heather999** [comment]
On Slack Simon notes the validateDrp inputs:
_calexps and src files. It can use jointcal outputs if available._
https://lsstc.slack.com/archives/C978LTJGN/p1526317672000458

**Comment by heather999** [comment]
We should also keep an eye on https://github.com/LSSTDESC/DC2_Repo/issues/52

**Comment by wmwv** [comment]
Things to transfer from IN2P3 `/sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_18/data` to NERSC:
```
input/_mapper
input/config
input/registry.sqlite3
input/ref_cats
output/calexp
output/config
output/deepCoadd
output/processEimage_metadata
output/schema
```

* Notes on filepaths:  
 - The `registry.sqlite3` file does not contain file paths.  It merely contains the information necessary to construct the filename _within_ a repository:
```
id|visit|channel|snap|sensor|ccd|raft|filter|taiObs|expTime
1|221612|0,7|0|0,0|0,0|2,3|g|2022-10-27T04:48:16.827199744|30.0
2|221612|1,2|0|1,0|1,0|1,2|g|2022-10-27T04:48:16.827199744|30.0
3|221612|0,1|0|1,0|1,0|1,3|g|2022-10-27T04:48:16.827199744|30.0
4|221612|0,4|0|1,0|1,0|1,3|g|2022-10-27T04:48:16.827199744|30.0
5|221612|0,5|0|1,0|1,0|0,1|g|2022-10-27T04:48:16.827199744|30.0
6|221612|1,4|0|2,0|2,0|0,2|g|2022-10-27T04:48:16.827199744|30.0
7|221612|1,4|0|2,0|2,0|1,3|g|2022-10-27T04:48:16.827199744|30.0
8|221612|1,0|0|0,2|0,2|2,2|g|2022-10-27T04:48:16.827199744|30.0
9|221612|1,0|0|0,1|0,1|0,3|g|2022-10-27T04:48:16.827199744|30.0
10|221612|0,5|0|0,2|0,2|1,3|g|2022-10-27T04:48:16.827199744|30.0
```

 - As @airnandez noted during the call, there is some path-dependence in the repository.  The filepath issue comes up when trying to read from a child "repo/rerun" to its parent.  Specifically, this relationship is in the `repositoryCfg.yaml` file.  E.g., there is a `output/repositoryCfg.yaml` file that contains a `root` entry that points to the directory on the IN2P3 machines:
```
/afs/in2p3.fr/home/w/wmwv/DC2/Run1.2p/data(0)>cat output/repositoryCfg.yaml
!RepositoryCfg_v1
_mapper: &id001 !!python/name:lsst.obs.lsstSim.lsstSimMapper.LsstSimMapper ''
_mapperArgs: {}
_parents:
- !RepositoryCfg_v1
  _mapper: *id001
  _mapperArgs: {}
  _parents: []
  _policy: null
  _root: /sps/lsst/dataproducts/desc/DC2/Run1.2p/w_2018_18/data/input
  dirty: true
_policy: null
_root: null
dirty: true
```

This means is that trying to access a raw image from the `output` "rerun"/"repo" will fail.  But it was going to fail anyway because we didn't even transfer those images.

Within the `output` "repo/rerun", there is no lookup of the parent, so this shouldn't be an issue when we, e.g., read a coadd image and want to look up something about one of the calexps that went into it.

And, eventually, we could edit this file to update the `root` to point to the correct directory on NERSC.
